name: test
on: push

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}, node ${{ matrix.node }}

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
